import fs from "fs";
import { getManifestPath, ensureProjectAgentsDir } from "./paths.js";
import { Platform } from "./platform.js";

export interface AgentEntry {
  version: string;
  installedAt: string;
}

export interface Manifest {
  _comment?: string;
  version: string;
  installedAt: string;
  platform?: Platform;
  agents: Record<string, AgentEntry>;
}

const MANIFEST_COMMENT =
  "This file is auto-generated by blue-gardener. Do not edit manually. Run 'npx blue-gardener repair' if issues occur.";

/**
 * Read the manifest file, returns null if it doesn't exist
 */
export function readManifest(): Manifest | null {
  const manifestPath = getManifestPath();

  if (fs.existsSync(manifestPath)) {
    const content = fs.readFileSync(manifestPath, "utf-8");
    return JSON.parse(content) as Manifest;
  }

  return null;
}

/**
 * Write the manifest file
 */
export function writeManifest(manifest: Manifest): void {
  ensureProjectAgentsDir();
  const manifestPath = getManifestPath();
  // Ensure comment is always present
  const manifestWithComment = {
    _comment: MANIFEST_COMMENT,
    ...manifest,
  };
  fs.writeFileSync(
    manifestPath,
    JSON.stringify(manifestWithComment, null, 2) + "\n"
  );
}

/**
 * Create a new empty manifest
 */
export function createManifest(version: string, platform?: Platform): Manifest {
  return {
    _comment: MANIFEST_COMMENT,
    version,
    installedAt: new Date().toISOString(),
    platform,
    agents: {},
  };
}

/**
 * Update platform in manifest
 */
export function updatePlatform(
  manifest: Manifest,
  platform: Platform
): Manifest {
  return {
    ...manifest,
    platform,
  };
}

/**
 * Add an agent to the manifest
 */
export function addAgentToManifest(
  manifest: Manifest,
  agentName: string,
  version: string
): Manifest {
  return {
    ...manifest,
    agents: {
      ...manifest.agents,
      [agentName]: {
        version,
        installedAt: new Date().toISOString(),
      },
    },
  };
}

/**
 * Remove an agent from the manifest
 */
export function removeAgentFromManifest(
  manifest: Manifest,
  agentName: string
): Manifest {
  const { [agentName]: _, ...remainingAgents } = manifest.agents;
  return {
    ...manifest,
    agents: remainingAgents,
  };
}

/**
 * Get list of installed agent names
 */
export function getInstalledAgentNames(): string[] {
  const manifest = readManifest();
  if (!manifest) {
    return [];
  }
  return Object.keys(manifest.agents);
}
